export const PUERTO_OFICIAL = 53317
export const DIRECCION_BROADCAST = '255.255.255.255'
export const LIMITE_INACTIVIDAD_MS = 12000
export const INTERVALO_LIMPIEZA_MS = 5000
export const ACCION_NEGOCIAR = 'SOLICITAR_TRANSFERENCIA'
export const ACCION_CONFIRMAR = 'RESPONDER_TRANSFERENCIA'
export const ESTADO_ACEPTADO = 'ACEPTADO'
export const ESTADO_RECHAZADO = 'RECHAZADO'
